### PR TITLE
Fix URL of inline image select

### PR DESCRIPTION
**Pull request by eduardoboucas**
Fixes the URL of the inline image select view when creating new documents.

### CODE REVIEW

**Comment by davidmacp** [comment]
@eduardoboucas if I try to add an inline image through the test suite using the localhost instance that gets spun up, I am seeing the following error in console after I press `Insert image` on the select image screen

```
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.
    at RichEditor.value (bundle.js:5)
    at RichEditor.value (bundle.js:5)
    at FieldStringEdit.value (bundle.js:5)
    at flushMounts (bundle.js:1)
    at renderComponent (bundle.js:1)
    at Router.forceUpdate (bundle.js:1)
    at Router.routeTo (bundle.js:1)
    at bundle.js:1
    at bundle.js:1
    at dispatch (bundle.js:1)
```

**Comment by jimlambie** [comment]
The problem here is probably caused by pressing Enter twice before trying to insert an image. If you press Enter once then insert an image, it works. 

The error occurs in L318 of RichEditor.jsx, where the baseNode is assigned by getting the editor's childNodes at an index that is 1 too high for the number of childNodes

**Comment by jimlambie** [comment]
@eduardoboucas I added a fix in the `serialiseSelection` method, for your review when you get a moment please! 🌮

**Comment by davidmacp** [comment]
Added new Inline Image test to this PR as discussed with @jimlambie

**Pull request merged**
