### PR TITLE
Fix flashing upload drop zone

### LINKED ISSUE #416: File upload drop target issue
### Expected behavior
Should be a way to drop files into a file upload

### Actual behavior
The drop target changes quickly and makes it difficult to drop

### Steps to reproduce the problem
Drop a file onto the drop target on an upload screen!

### Package details
`develop` branch once #393 is closed / #415 is merged

### PR DESCRIPTION
**Pull request by danwdart**
Fixes #416

### CODE REVIEW

**Comment by danwdart** [comment]
There are many unrelated tests breaking

**Comment by eduardoboucas** [comment]
As discussed on the Publish call, I'm happy to merge this and we can revisit if we're still not happy with the result.

I see some merge conflicts now, is this something you could fix?

**Comment by danwdart** [comment]
Yep of course

**Comment by eduardoboucas** [comment]
I think the change was done by @anaumovets as part of #435. From what I gather, the newly-created `accept` variable is the same as drilling into `config`, except it's safeguarded against missing schema properties.

If that doesn't make sense, it's probably worth asking him.

**Comment by danwdart** [comment]
Okay that did it

**Pull request merged**
